# sample comes from https://github.com/docker/awesome-compose

services:
  frontend:
    image: excalidraw:latest
    ports:
      - 8080:80
  storage:
    image: yinhuihe/excalidraw-storage-backend:latest
    restart: always
    environment:
      STORAGE_URI: redis://user:pass@localhost:6379
    ports:
      - 8081:8080
  room:
    image: yinhuihe/excalidraw-room:latest
    ports:
      - 8082:80
